name: Run autotests


on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select test to run
        required: true
        type: choice
        default: all
        options:
          - all


jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Tests
    steps:
      - name: copy source code
        uses: actions/checkout@v4
      - name: Set up Python eny
        uses: actions/setuo-pythone@v5
        with: 
          python-version: "3.12"
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -v
